# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/media/ysera/Extreme SSD/sandbox/Tesseract"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/media/ysera/Extreme SSD/sandbox/Tesseract"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/media/ysera/Extreme SSD/sandbox/Tesseract/CMakeFiles" "/media/ysera/Extreme SSD/sandbox/Tesseract//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/media/ysera/Extreme SSD/sandbox/Tesseract/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Tesseract

# Build rule for target.
Tesseract: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Tesseract
.PHONY : Tesseract

# fast build rule for target.
Tesseract/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tesseract.dir/build.make CMakeFiles/Tesseract.dir/build
.PHONY : Tesseract/fast

#=============================================================================
# Target rules for targets named spdlog

# Build rule for target.
spdlog: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 spdlog
.PHONY : spdlog

# fast build rule for target.
spdlog/fast:
	$(MAKE) $(MAKESILENT) -f lib/spdlog/CMakeFiles/spdlog.dir/build.make lib/spdlog/CMakeFiles/spdlog.dir/build
.PHONY : spdlog/fast

#=============================================================================
# Target rules for targets named imgui

# Build rule for target.
imgui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 imgui
.PHONY : imgui

# fast build rule for target.
imgui/fast:
	$(MAKE) $(MAKESILENT) -f lib/imgui/CMakeFiles/imgui.dir/build.make lib/imgui/CMakeFiles/imgui.dir/build
.PHONY : imgui/fast

src/Sandbox/SandboxApp.o: src/Sandbox/SandboxApp.cpp.o
.PHONY : src/Sandbox/SandboxApp.o

# target to build an object file
src/Sandbox/SandboxApp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tesseract.dir/build.make CMakeFiles/Tesseract.dir/src/Sandbox/SandboxApp.cpp.o
.PHONY : src/Sandbox/SandboxApp.cpp.o

src/Sandbox/SandboxApp.i: src/Sandbox/SandboxApp.cpp.i
.PHONY : src/Sandbox/SandboxApp.i

# target to preprocess a source file
src/Sandbox/SandboxApp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tesseract.dir/build.make CMakeFiles/Tesseract.dir/src/Sandbox/SandboxApp.cpp.i
.PHONY : src/Sandbox/SandboxApp.cpp.i

src/Sandbox/SandboxApp.s: src/Sandbox/SandboxApp.cpp.s
.PHONY : src/Sandbox/SandboxApp.s

# target to generate assembly for a file
src/Sandbox/SandboxApp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tesseract.dir/build.make CMakeFiles/Tesseract.dir/src/Sandbox/SandboxApp.cpp.s
.PHONY : src/Sandbox/SandboxApp.cpp.s

src/core/Application.o: src/core/Application.cpp.o
.PHONY : src/core/Application.o

# target to build an object file
src/core/Application.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tesseract.dir/build.make CMakeFiles/Tesseract.dir/src/core/Application.cpp.o
.PHONY : src/core/Application.cpp.o

src/core/Application.i: src/core/Application.cpp.i
.PHONY : src/core/Application.i

# target to preprocess a source file
src/core/Application.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tesseract.dir/build.make CMakeFiles/Tesseract.dir/src/core/Application.cpp.i
.PHONY : src/core/Application.cpp.i

src/core/Application.s: src/core/Application.cpp.s
.PHONY : src/core/Application.s

# target to generate assembly for a file
src/core/Application.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tesseract.dir/build.make CMakeFiles/Tesseract.dir/src/core/Application.cpp.s
.PHONY : src/core/Application.cpp.s

src/core/EntryPoint.o: src/core/EntryPoint.cpp.o
.PHONY : src/core/EntryPoint.o

# target to build an object file
src/core/EntryPoint.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tesseract.dir/build.make CMakeFiles/Tesseract.dir/src/core/EntryPoint.cpp.o
.PHONY : src/core/EntryPoint.cpp.o

src/core/EntryPoint.i: src/core/EntryPoint.cpp.i
.PHONY : src/core/EntryPoint.i

# target to preprocess a source file
src/core/EntryPoint.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tesseract.dir/build.make CMakeFiles/Tesseract.dir/src/core/EntryPoint.cpp.i
.PHONY : src/core/EntryPoint.cpp.i

src/core/EntryPoint.s: src/core/EntryPoint.cpp.s
.PHONY : src/core/EntryPoint.s

# target to generate assembly for a file
src/core/EntryPoint.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tesseract.dir/build.make CMakeFiles/Tesseract.dir/src/core/EntryPoint.cpp.s
.PHONY : src/core/EntryPoint.cpp.s

src/core/ImGuiLayer.o: src/core/ImGuiLayer.cpp.o
.PHONY : src/core/ImGuiLayer.o

# target to build an object file
src/core/ImGuiLayer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tesseract.dir/build.make CMakeFiles/Tesseract.dir/src/core/ImGuiLayer.cpp.o
.PHONY : src/core/ImGuiLayer.cpp.o

src/core/ImGuiLayer.i: src/core/ImGuiLayer.cpp.i
.PHONY : src/core/ImGuiLayer.i

# target to preprocess a source file
src/core/ImGuiLayer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tesseract.dir/build.make CMakeFiles/Tesseract.dir/src/core/ImGuiLayer.cpp.i
.PHONY : src/core/ImGuiLayer.cpp.i

src/core/ImGuiLayer.s: src/core/ImGuiLayer.cpp.s
.PHONY : src/core/ImGuiLayer.s

# target to generate assembly for a file
src/core/ImGuiLayer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tesseract.dir/build.make CMakeFiles/Tesseract.dir/src/core/ImGuiLayer.cpp.s
.PHONY : src/core/ImGuiLayer.cpp.s

src/core/Layer.o: src/core/Layer.cpp.o
.PHONY : src/core/Layer.o

# target to build an object file
src/core/Layer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tesseract.dir/build.make CMakeFiles/Tesseract.dir/src/core/Layer.cpp.o
.PHONY : src/core/Layer.cpp.o

src/core/Layer.i: src/core/Layer.cpp.i
.PHONY : src/core/Layer.i

# target to preprocess a source file
src/core/Layer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tesseract.dir/build.make CMakeFiles/Tesseract.dir/src/core/Layer.cpp.i
.PHONY : src/core/Layer.cpp.i

src/core/Layer.s: src/core/Layer.cpp.s
.PHONY : src/core/Layer.s

# target to generate assembly for a file
src/core/Layer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tesseract.dir/build.make CMakeFiles/Tesseract.dir/src/core/Layer.cpp.s
.PHONY : src/core/Layer.cpp.s

src/core/Logger.o: src/core/Logger.cpp.o
.PHONY : src/core/Logger.o

# target to build an object file
src/core/Logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tesseract.dir/build.make CMakeFiles/Tesseract.dir/src/core/Logger.cpp.o
.PHONY : src/core/Logger.cpp.o

src/core/Logger.i: src/core/Logger.cpp.i
.PHONY : src/core/Logger.i

# target to preprocess a source file
src/core/Logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tesseract.dir/build.make CMakeFiles/Tesseract.dir/src/core/Logger.cpp.i
.PHONY : src/core/Logger.cpp.i

src/core/Logger.s: src/core/Logger.cpp.s
.PHONY : src/core/Logger.s

# target to generate assembly for a file
src/core/Logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tesseract.dir/build.make CMakeFiles/Tesseract.dir/src/core/Logger.cpp.s
.PHONY : src/core/Logger.cpp.s

src/core/Window.o: src/core/Window.cpp.o
.PHONY : src/core/Window.o

# target to build an object file
src/core/Window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tesseract.dir/build.make CMakeFiles/Tesseract.dir/src/core/Window.cpp.o
.PHONY : src/core/Window.cpp.o

src/core/Window.i: src/core/Window.cpp.i
.PHONY : src/core/Window.i

# target to preprocess a source file
src/core/Window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tesseract.dir/build.make CMakeFiles/Tesseract.dir/src/core/Window.cpp.i
.PHONY : src/core/Window.cpp.i

src/core/Window.s: src/core/Window.cpp.s
.PHONY : src/core/Window.s

# target to generate assembly for a file
src/core/Window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tesseract.dir/build.make CMakeFiles/Tesseract.dir/src/core/Window.cpp.s
.PHONY : src/core/Window.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tesseract.dir/build.make CMakeFiles/Tesseract.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tesseract.dir/build.make CMakeFiles/Tesseract.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tesseract.dir/build.make CMakeFiles/Tesseract.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Tesseract"
	@echo "... imgui"
	@echo "... spdlog"
	@echo "... src/Sandbox/SandboxApp.o"
	@echo "... src/Sandbox/SandboxApp.i"
	@echo "... src/Sandbox/SandboxApp.s"
	@echo "... src/core/Application.o"
	@echo "... src/core/Application.i"
	@echo "... src/core/Application.s"
	@echo "... src/core/EntryPoint.o"
	@echo "... src/core/EntryPoint.i"
	@echo "... src/core/EntryPoint.s"
	@echo "... src/core/ImGuiLayer.o"
	@echo "... src/core/ImGuiLayer.i"
	@echo "... src/core/ImGuiLayer.s"
	@echo "... src/core/Layer.o"
	@echo "... src/core/Layer.i"
	@echo "... src/core/Layer.s"
	@echo "... src/core/Logger.o"
	@echo "... src/core/Logger.i"
	@echo "... src/core/Logger.s"
	@echo "... src/core/Window.o"
	@echo "... src/core/Window.i"
	@echo "... src/core/Window.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

